using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//to use textTMP
using TMPro;
//to manager the scene
using UnityEngine.SceneManagement;
//to use button
using UnityEngine.UI;

public class GameManager : MonoBehaviour
{
    private float spawnRate = 1.0f;
    private int score;

    public List<GameObject> targetsList;

    //reference to the text on the canvas
    public TextMeshProUGUI scoreText;
    public TextMeshProUGUI gameOverText;
    public bool isGameActive;
    public Button restartButton;
    public GameObject titleScreen;


    // Start is called before the first frame update
    void Start()
    {
        
    }


    IEnumerator SpawnTarguet()
    {

        while (isGameActive)
        {
            yield return new WaitForSeconds(spawnRate);
            int index = Random.Range(0, targetsList.Count);
            // since the position and rotations are generated by the target script here, we just need to instantiate the objects
            Instantiate(targetsList[index]);
        }

    }

    public void UpdateScore(int points)
    {
        score += points;
        scoreText.text = "Score: " + score;
    }
        
    public void GameOver()
    {
        gameOverText.gameObject.SetActive(true);
        restartButton.gameObject.SetActive(true);
        isGameActive = false;
    }

    public void RestartGame()
    {
        //it is goint to load the current scene
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void StartGame(int difficulty)
    {
        spawnRate /= difficulty;
        isGameActive = true;//needs to be at the top because of the coroutine.
        StartCoroutine(SpawnTarguet());
        score = 0;
        //reference to the text on the canvas
        scoreText.text = "Score: " + score;
        titleScreen.SetActive(false);
    }


}
